/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_admin_authentification (void);
GtkWidget* create_saisie_coordonnee (void);
GtkWidget* create_CRUD_admin (void);
GtkWidget* create_admin_page_accueil (void);
GtkWidget* create_aff_listes (void);
GtkWidget* create_mdp_oublie (void);
GtkWidget* create_ibtihel_reclamation (void);
GtkWidget* create_ibtihel_ajou_rec (void);
GtkWidget* create_gestionsdeselections (void);
GtkWidget* create_affichage_election (void);
GtkWidget* create_ajout_election (void);
GtkWidget* create_modif_election (void);
GtkWidget* create_Bv_page_d_acceuil (void);
GtkWidget* create_bv_ajoutunbureau (void);
GtkWidget* create_bv_modifierunbureau (void);
GtkWidget* create_ibtihel_modif_rec (void);
GtkWidget* create_ibti_msg_supp (void);
GtkWidget* create_Bv_affinterface (void);
GtkWidget* create_sami_gl_window_acceuil (void);
GtkWidget* create_sami_gl_window_aj (void);
GtkWidget* create_sami_gl_window_modifier (void);
GtkWidget* create_sami_gl_window_gestion (void);
GtkWidget* create_gl_sami_window_vote (void);
GtkWidget* create_gl_window_confirmation_supp (void);
GtkWidget* create_window_statistique (void);
GtkWidget* create_saisie_coordonnee_modif (void);
