/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *admin_authentification;
  GtkWidget *saisie_coordonnee;
  GtkWidget *CRUD_admin;
  GtkWidget *admin_page_accueil;
  GtkWidget *aff_listes;
  GtkWidget *mdp_oublie;
  GtkWidget *ibtihel_reclamation;
  GtkWidget *ibtihel_ajou_rec;
  GtkWidget *gestionsdeselections;
  GtkWidget *affichage_election;
  GtkWidget *ajout_election;
  GtkWidget *modif_election;
  GtkWidget *Bv_page_d_acceuil;
  GtkWidget *bv_ajoutunbureau;
  GtkWidget *bv_modifierunbureau;
  GtkWidget *ibtihel_modif_rec;
  GtkWidget *ibti_msg_supp;
  GtkWidget *Bv_affinterface;
  GtkWidget *sami_gl_window_acceuil;
  GtkWidget *sami_gl_window_aj;
  GtkWidget *sami_gl_window_modifier;
  GtkWidget *sami_gl_window_gestion;
  GtkWidget *gl_sami_window_vote;
  GtkWidget *gl_window_confirmation_supp;
  GtkWidget *window_statistique;
  GtkWidget *saisie_coordonnee_modif;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  admin_authentification = create_admin_authentification ();
  gtk_widget_show (admin_authentification);
  /*saisie_coordonnee = create_saisie_coordonnee ();
  gtk_widget_show (saisie_coordonnee);
  saisie_coordonnee_modif = create_saisie_coordonnee_modif ();
  gtk_widget_show (saisie_coordonnee_modif);
  CRUD_admin = create_CRUD_admin ();
  gtk_widget_show (CRUD_admin);
  admin_page_accueil = create_admin_page_accueil ();
  gtk_widget_show (admin_page_accueil);
  aff_listes = create_aff_listes ();
  gtk_widget_show (aff_listes);
  mdp_oublie = create_mdp_oublie ();
  gtk_widget_show (mdp_oublie);
  ibtihel_reclamation = create_ibtihel_reclamation ();
  gtk_widget_show (ibtihel_reclamation);
  ibtihel_ajou_rec = create_ibtihel_ajou_rec ();
  gtk_widget_show (ibtihel_ajou_rec);
  gestionsdeselections = create_gestionsdeselections ();
  gtk_widget_show (gestionsdeselections);
  affichage_election = create_affichage_election ();
  gtk_widget_show (affichage_election);
  ajout_election = create_ajout_election ();
  gtk_widget_show (ajout_election);
  modif_election = create_modif_election ();
  gtk_widget_show (modif_election);
  Bv_page_d_acceuil = create_Bv_page_d_acceuil ();
  gtk_widget_show (Bv_page_d_acceuil);
  bv_ajoutunbureau = create_bv_ajoutunbureau ();
  gtk_widget_show (bv_ajoutunbureau);
  bv_modifierunbureau = create_bv_modifierunbureau ();
  gtk_widget_show (bv_modifierunbureau);
  ibtihel_modif_rec = create_ibtihel_modif_rec ();
  gtk_widget_show (ibtihel_modif_rec);
  ibti_msg_supp = create_ibti_msg_supp ();
  gtk_widget_show (ibti_msg_supp);
Bv_affinterface = create_Bv_affinterface ();
  gtk_widget_show (Bv_affinterface);
  sami_gl_window_acceuil = create_sami_gl_window_acceuil ();
  gtk_widget_show (sami_gl_window_acceuil);
 sami_gl_window_aj = create_sami_gl_window_aj ();
  gtk_widget_show (sami_gl_window_aj);
  sami_gl_window_modifier = create_sami_gl_window_modifier ();
  gtk_widget_show (sami_gl_window_modifier);
  sami_gl_window_gestion = create_sami_gl_window_gestion ();
  gtk_widget_show (sami_gl_window_gestion);
  gl_sami_window_vote = create_gl_sami_window_vote ();
  gtk_widget_show (gl_sami_window_vote);
  gl_window_confirmation_supp = create_gl_window_confirmation_supp ();
  gtk_widget_show (gl_window_confirmation_supp);
  window_statistique=create_window_statistique ();
  gtk_widget_show (window_statistique); */

  gtk_main ();
  return 0;
}

